name: CI/CD Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  # Job de pruebas (CI)
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "test_main.py"

    - name: Run static analysis (PEP8)
      run: |
        flake8 . --max-line-length=79 --ignore=E501


  # Job de despliegue (CD)
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: fastapi
      PROJECT_ID: ${{ secrets.GOOGLE_PROJECT }} 

    needs: test

    steps:
    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-west2-docker.pkg.dev
        docker build -t us-west2-docker.pkg.dev/$GOOGLE_PROJECT/images/$IMAGE_NAME:latest .
        docker push us-west2-docker.pkg.dev/$GOOGLE_PROJECT/images/$IMAGE_NAME:latest

    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud container clusters get-credentials autopilot-cluster-1 --region us-west2
        docker pull us-west2-docker.pkg.dev/$GOOGLE_PROJECT/images/$IMAGE_NAME:latest
        kubectl apply -f resources.yaml
